# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-HTTunnel
version:      0.02
version_from: lib/Apache/HTTunnel.pm
installdirs:  site
requires:
    File::FDkeeper:                0
    mod_perl:                      1.999021

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
